#!/usr/bin/env bash
# This script is displaying "Best School"  times, "good luck, bad luck" on iterations 4 and 8, non respectvely.

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
	    echo "Best School"
	fi
	i=$((i+1))
done

